#!/bin/bash

SCRIPTPATH="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"

echo ${DOCKERFILE_PATH}

case $DOCKERFILE_PATH in
    "dockerfiles/apache/Dockerfile") SERVER_FLAVOR="apache";;
    "dockerfiles/fpm_alpine/Dockerfile") SERVER_FLAVOR="fpm_alpine";;
esac

# File must end with new line
FILE="${SCRIPTPATH}/../versions.txt"
echo >> "${FILE}"

DB_FLAVORS=("mysqli" "pgsql" "all")

while read -r VERSION; do

    echo "BUILDING ${VERSION}"
    if [ "${VERSION}" == "" ]; then
        continue
    fi
    for DB_TYPE in "${DB_FLAVORS[@]}"; do

        DB_FLAVOR=""
        case $DB_TYPE in
            "mysqli" ) DB_FLAVOR="mysql_maria" ;;
            "pgsql" ) DB_FLAVOR="postgresql" ;;
            *) DB_FLAVOR="mulitbase"
        esac    

        VERSION_TAG="-t ellakcy/moodle:${DB_FLAVOR}_${SERVER_FLAVOR}_${VERSION}"

        VERSION_TYPE_TAG=""

        if [[ $VERSION == $LATEST_LTS ]]; then
            VERSION_TYPE_TAG="-t ellakcy/moodle:${DB_FLAVOR}_${SERVER_FAVOR}_lts"
        fi

        if [[ $VERSION == $LATEST ]]; then
            VERSION_TYPE_TAG="${VERSION_TYPE_TAG} -t ellakcy/moodle:${DB_FLAVOR}_${SERVER_FAVOR}_latest -t ellakcy/moodle:${DB_FLAVOR}_${SERVER_FAVOR}" 
            if [[ $SERVER_FAVOR == "apache" ]] && [[ $DB_FLAVOR = "mulitbase" ]]; then
                VERSION_TYPE_TAG=" ${VERSION_TYPE_TAG} -t  ellakcy/moodle:latest"
            fi
        fi

        echo "docker build --build-arg VERSION=${VERSION} --build-arg DB_TYPE=${DB_TYPE} -f ${DOCKERFILE_PATH} ${VERSION_TYPE_TAG} ${VERSION_TAG} --force-rm ."
        docker build -f ${DOCKERFILE_PATH} ${VERSION_TYPE_TAG} ${VERSION_TAG} --force-rm ${SCRIPTPATH}/..
    done
done < "${FILE}"

