#!/bin/bash

VERSIONS=(35 36 37 38)
DOCKERFILES=("dockerfiles/apache/Dockerfile" "dockerfiles/fpm_alpine/Dockerfile")
DB_FLAVORS=("mysqli" "pgsql" "all")

LATEST=38
LATEST_LTS=35

for VERSION in "${VERSIONS[@]}"; do
    for DOCKERFILE in "${DOCKERFILES[@]}"; do
        for DB_TYPE in "${DB_FLAVORS[@]}"; do

            # if [[ $DOCKERFILE == $DOCKERFILE_ALPINE_FPM ]]; then
            #     SERVER_FLAVOR="fpm_alpine"
            # fi

            case $DOCKERFILE in
                "dockerfiles/apache/Dockerfile") SERVER_FLAVOR="apache";;
                "dockerfiles/fpm_alpine/Dockerfile") SERVER_FLAVOR="fpm_alpine";;
            esac

            DB_FLAVOR=""
            case $DB_TYPE in
                "mysqli" ) DB_FLAVOR="mysql_maria" ;;
                "pgsql" ) DB_FLAVOR="postgresql" ;;
                *) DB_FLAVOR="mulitbase"
            esac

            VERSION_TAG="-t ellakcy/moodle:${DB_FLAVOR}_${SERVER_FLAVOR}_${VERSION}"

            VERSION_TYPE_TAG=""

            case "$VERSION" in
                "${LATEST_LTS}" ) VERSION_TYPE_TAG="-t ellakcy/moodle:${DB_FLAVOR}_${SERVER_FLAVOR}_lts" ;;
                "${LATEST}" ) VERSION_TYPE_TAG="-t ellakcy/moodle:${DB_FLAVOR}_${SERVER_FLAVOR}_latest -t ellakcy/moodle:${DB_FLAVOR}_${SERVER_FLAVOR}"
                 if [[ $SERVER_FLAVOR == "apache" ]] && [[ $DB_FLAVOR = "mulitbase" ]]; then
                    echo "TAG LATEST"
                    VERSION_TYPE_TAG=" ${VERSION_TYPE_TAG} -t  ellakcy/moodle:latest"
                fi;;
            esac 

            echo "docker build --build-arg VERSION=${VERSION} --build-arg DB_TYPE=${DB_TYPE} -f ${DOCKERFILE} ${VERSION_TYPE_TAG} ${VERSION_TAG} --no-cache --force-rm ."
            docker build -f ${DOCKERFILE} ${VERSION_TYPE_TAG} ${VERSION_TAG} --no-cache --force-rm .
        done
    done
done