name: deploy-fpm

on:
  schedule:
    - cron: 23 20 * * 6 
  push:
    branches: [ master, dev ]

jobs:
  build_images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        moodle_version: [401,404,405,500]
        php_version: [8.0,8.1,8.2,8.3,8.4]
        exclude:
          
          - moodle_version: 404
            php_version: 8.0
          - moodle_version: 405
            php_version: 8.0
          - moodle_version: 500
            php_version: 8.0
          - moodle_version: 500
            php_version: 8.1
    env:
      VERSION: ${{ matrix.moodle_version }}
      PHP_VERSION: "${{ matrix.php_version }}"
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        if: github.ref != 'refs/heads/dev'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Images
        shell: bash
        run: |
          docker --version
          chmod +x ".github/build_docker.sh"
          .github/build_docker.sh 

